[package]
name = "shared-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true


[dependencies]
near-sdk.workspace = true
strum = { workspace = true, features = ["derive"] }
chrono.workspace = true
