[package]
name = "slothrace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
chrono = "0.4.38"
envy = "0.4.2"
hex = "0.4.3"
octocrab = "0.38.0"
dotenv = "0.15"
serde = { version = "1.0.199", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
env_logger = "0.11.3"
log = "0.4.21"
