[package]
name = "race-of-sloths-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rocket = { workspace = true, features = ["json"] }
svg.workspace = true
