[package]
name = "slothrace"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
envy.workspace = true
hex.workspace = true
octocrab.workspace = true
dotenv.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
env_logger.workspace = true
tracing.workspace = true
async-trait.workspace = true
near-workspaces.workspace = true
serde_json.workspace = true
futures.workspace = true
shared-types.workspace = true
rand.workspace = true
